export const topicNouns = {
  metadata: {
    totalCategories: 20,
    wordsPerCategory: 300,
    totalWords: 6000,
    language: "English",
    type: "Scenario-based Nouns"
  },
  scenarios: {
    kitchen: [
      "refrigerator", "stove", "oven", "microwave", "toaster", "blender", "kettle", "mixer", "dishwasher", "sink",
      "faucet", "cabinet", "drawer", "countertop", "pantry", "plate", "bowl", "cup", "mug", "glass",
      "spoon", "fork", "knife", "spatula", "whisk", "ladle", "peeler", "grater", "colander", "cuttingboard",
      "fryingpan", "saucepan", "pot", "lid", "bakingsheet", "rollingpin", "apron", "ovenmitt", "sponge", "dishcloth",
      "trashcan", "recyclingbin", "papertowel", "aluminumfoil", "plasticwrap", "ziplocbag", "jar", "container", "thermos", "corkscrew",
      "bottleopener", "canopener", "tongs", "scissors", "funnel", "timer", "scale", "thermometer", "coffeemaker", "espressomachine",
      "juicer", "ricecooker", "slowcooker", "airfryer", "wafflemaker", "griddle", "mortar", "pestle", "teapot", "sugarbowl",
      "creamer", "butterdish", "saltshaker", "peppermill", "spicerack", "napkin", "tablecloth", "placemat", "tray", "trivet",
      "dishrack", "soapdispenser", "steelwool", "scourer", "pitcher", "carafe", "decanter", "garlicpress", "potatomasher", "saladspinner",
      "icecubetray", "garlickeeper", "breadbox", "knifeblock", "eggcup", "honeydipper", "lemonsqueezer", "teastrainer", "coffeefilter", "coals",
      "cooktop", "rangehood", "broiler", "skillet", "pressurecooker", "steamer", "dehydrator", "fonduepot", "crepemaker", "sandwichpress",
      "paninipress", "eggboiler", "popcornmaker", "icecreamman", "breadmaker", "meatgrinder", "slicingmachine", "canister", "cookiecutter", "tartpan",
      "muffinpan", "piepan", "loafpan", "springformpan", "ramekin", "casserole", "dutchoven", "wok", "roastingpan", "grillpan",
      "gravyboat", "butterknife", "steakknife", "breadknife", "paringknife", "cleaver", "shears", "honingrod", "block", "potholder",
      "coffeegrinder", "milkfrother", "teainfuser", "icedteamaker", "sodastream", "waterfilter", "faucethead", "winecooler", "beerdispenser", "compactor",
      "greasejar", "scrubber", "dishwashingliquid", "rinseaid", "cleanser", "cloth", "towel", "rag", "thermocouple", "gasket",
      "knob", "burner", "grate", "rack", "drippan", "deflector", "spit", "rotisserie", "skewer", "bastingbrush",
      "injector", "thermopen", "shaker", "cruet", "saucebottle", "saltcellar", "pepperbox", "spicejar", "lazysusan", "holder",
      "hook", "shelf", "liner", "mat", "cozy", "coasters", "napkinring", "tablerunner", "cover", "protector",
      "cloche", "dome", "server", "lifter", "turner", "skimmer", "spider", "strainer", "sifter", "masher",
      "ricer", "press", "crusher", "grinder", "mill", "zester", "corer", "scoop", "melonballer", "doughscraper",
      "benchknife", "brush", "oilcan", "dropper", "pipette", "beaker", "measuringcup", "measuringspoon", "jigger", "muddler",
      "pourer", "stopper", "cork", "sealer", "foilcutter", "pump", "chiller", "bucket", "icebucket", "tong",
      "cooler", "sleeve", "bag", "carrier", "tote", "organizer", "insert", "divider", "riser", "basket",
      "bin", "crate", "can", "tub", "pail", "caddy", "rail", "bar", "magnet", "strip",
      "stopwatch", "clock", "notepad", "pen", "clip", "bagclip", "tie", "band", "wrap", "foil",
      "parchment", "waxpaper", "butcherpaper", "string", "bakingstone", "pastrybrush", "flourbin", "sugarbin", "garbagedisposal", "drainplug",
      "sinkstrainer", "utilitycart", "wineholder", "stemwarerack", "measuringjug", "butterwarmer", "chafingdish", "eggpoacher", "applepeeler", "plummet",
      "garlicpeeler", "herbstripper", "cherrypitter", "applecorer", "nutcracker", "seafoodcracker", "oystershucker", "fishscaler", "cheeseplane", "wirecutter",
      "baconpress", "tortillapress", "sushimat", "chopsticks", "ramenbowl", "saucedish", "sakecup", "bento", "lunchbox", "flamingtorch"
    ],

    bedroom: [
      "bed", "mattress", "pillow", "pillowcase", "sheet", "blanket", "duvet", "comforter", "bedspread", "quilt",
      "headboard", "nightstand", "lamp", "alarmclock", "wardrobe", "closet", "hanger", "dresser", "mirror", "drawer",
      "rug", "curtain", "blinds", "window", "door", "radiator", "airconditioner", "fan", "humidifier", "airpurifier",
      "bookshelf", "desk", "chair", "laptop", "charger", "outlet", "switch", "trashbin", "laundrybasket", "hamper",
      "slippers", "pajamas", "bathrobe", "jewelrybox", "perfume", "comb", "hairbrush", "makeupvanity", "tissuebox", "sleepingbag",
      "eyemask", "earplugs", "canopy", "footstool", "bench", "cushion", "pictureframe", "painting", "wallsticker", "dreamcatcher",
      "safe", "key", "wallet", "phone", "tablet", "headphones", "speaker", "book", "notebook", "diary",
      "pen", "pencil", "glasses", "watch", "calendar", "candle", "incense", "vase", "flower", "houseplant",
      "stuffedanimal", "toy", "boardgame", "puzzle", "socks", "sweater", "jacket", "hat", "belt", "shoehorn",
      "lintroller", "valetstand", "shoebox", "bedpost", "dustruffle", "chest", "trunk", "armchair", "throwblanket", "headphonestand",
      "skylight", "bolster", "sleepingpillow", "daybed", "bunkbed", "futon", "headboardlamp", "readinglight", "valet", "wardrobeorganizer",
      "tiehanger", "scarfhanger", "shoerack", "drawerdivider", "underbedstorage", "bedrisers", "weightedblanket", "fleeceblanket", "soundmachine", "diffuser",
      "essentialoil", "linenmirror", "dressingtable", "vanitystool", "jewelrytree", "ringholder", "eyeglassholder", "phonestand", "chargingstation", "powerstrip",
      "extensioncord", "wallhook", "doorstop", "curtainrod", "curtaintieback", "valance", "windowscreen", "radiatorcover", "floorfan", "ceilingfan",
      "spaceheater", "bedsidepocket", "shelf", "floatingcabinet", "footrest", "pouf", "accentchair", "rockingchair", "chaise", "loveseat",
      "trunkchest", "hopechest", "blanketbox", "accentrug", "sheepskinrug", "walltapestry", "photoalbum", "shadowbox", "clock", "weatherstation",
      "calendarholder", "letteropener", "wastebasket", "laundrybin", "laundrysorter", "clothespin", "mothballs", "cedarblocks", "perfumebottle", "colognebottle",
      "vanitytray", "cosmeticbag", "makeupbrush", "powderpuff", "hairtie", "bobbyclip", "scrunchie", "headband", "nightgown", "housecoat",
      "bedsocks", "sleepshirt", "onesie", "silkpillowcase", "bedskirt", "canopynet", "windchime", "bedtray", "laptopdesk", "readingpillow",
      "backrest", "bolsterpillow", "bodypillow", "electricblanket", "downcomforter", "duvetcover", "fittedsheet", "flatsheet", "mattresspad", "mattressprotector",
      "boxspring", "bedframe", "slats", "trundlebed", "crib", "bassinet", "changingtable", "rockinghorse", "toybox", "playmat",
      "nurserychair", "babyphone", "babyblanket", "diaperpail", "nightlight", "wallclock", "mirrorball", "lavalamp", "stringlights", "fairylights",
      "ledstrip", "projectorlamp", "starprojector", "glowstars", "accentlight", "deskorganizer", "pencilcup", "paperweight", "stationery", "journals",
      "sketchbook", "canvas", "easel", "paintbrushes", "paints", "palette", "clay", "sculpture", "figurine", "driedflowers",
      "potpourri", "incenseholder", "candleholder", "matches", "snuffer", "lighter", "ashbasket", "woodbox", "fireplacepoker", "coalbucket",
      "bellows", "screenshield", "heatershield", "safebox", "fireproofsafe", "keyring", "walletchain", "pursehook", "backpackhanger", "totebag",
      "duffelbag", "briefcase", "suitcases", "garmentbag", "travelpillow", "eyeshade", "whitesound", "sleepbuds", "fitnessband", "smartring",
      "watchbox", "jewelrycase", "trinketdish", "hairdryer", "haircurler", "handmirror", "pocketmirror", "magnifyingmirror", "tweezers", "nailfile",
      "clipper", "scissors", "sewingkit", "threads", "needles", "pins", "pincushion", "tapemeasure", "fabricscissors", "thimble", "buttonbox"
    ],

    bathroom: [
      "bathtub", "shower", "showerhead", "curtain", "sink", "faucet", "toilet", "toiletpaper", "toiletbrush", "plunger",
      "mirror", "cabinet", "shelf", "towel", "bathmat", "bathrobe", "slippers", "soap", "soapdish", "dispenser",
      "shampoo", "conditioner", "bodywash", "loofah", "sponge", "washcloth", "toothbrush", "toothpaste", "cup", "mouthwash",
      "dentalfloss", "razor", "shavingcream", "aftershave", "hairdryer", "straightener", "curlingiron", "comb", "hairbrush", "hairtie",
      "bobbybin", "tweezers", "nailclippers", "nailfile", "scissors", "cottonswab", "cottonpad", "tissue", "scale", "hamper",
      "wastebasket", "laundrydetergent", "fabricsoftener", "bleach", "clothespin", "clothesline", "dryingrack", "iron", "ironingboard", "steamer",
      "perfume", "cologne", "deodorant", "lotion", "moisturizer", "sunscreen", "facewash", "scrub", "facemask", "makeup",
      "foundation", "mascara", "eyeliner", "lipstick", "eyeshadow", "blush", "powder", "remover", "towelrack", "hook",
      "bathbomb", "bathsalts", "bubblebath", "pumicestone", "showercap", "drain", "stopper", "pipe", "plumbing", "waterheater",
      "disinfectant", "cleaner", "mop", "bucket", "broom", "dustpan", "gloves", "scrubbrush", "airfreshener", "bidet",
      "toiletseat", "flusher", "toilettank", "sinkdrain", "trap", "washbasin", "vanity", "medicinedrawer", "firstaidcabinet", "towelring",
      "bathsheet", "handtowel", "washrag", "bathmitt", "exfoliator", "pumice", "scrubber", "backbrush", "showercaddy", "suctionhook",
      "soapbasket", "shampooflask", "conditionerpump", "cleansingfoam", "toner", "serum", "essence", "eyecream", "facemist", "sheetmask",
      "claymask", "poresstrip", "lipbalm", "lipgloss", "lipliner", "concealer", "primer", "settingspray", "loosepowder", "bronzer",
      "highlighter", "eyebrowpencil", "eyebrowgel", "eyelashcurler", "falselashes", "lashglue", "makeupbrush", "beautyblender", "brushcleaner", "shavingbrush",
      "straightrazor", "electricshaver", "beardtrimmer", "nosehairtrimmer", "hairclipper", "detangler", "hairserum", "hairwax", "hairgel", "hairspray",
      "dryshampoo", "bobbyclip", "hairclaw", "scrunchie", "headband", "bathpillow", "tubtray", "bathcaddy", "diatomat", "toiletrug",
      "pedestalrug", "bodyfatscale", "tissuebox", "cottonballjar", "qtipholder", "mouthwashbottle", "toothbrushholder", "uvsanitizer", "flosser", "waterflosser",
      "tonguescraper", "denturecup", "denturecleaner", "mouthguard", "retainerbox", "contactlenscase", "lenssolution", "eyeedrops", "eardrops", "nasalspray",
      "bandaid", "antiseptic", "ointment", "thermometer", "hotwaterbottle", "heatingpad", "icepack", "turbantowel", "hairwrap", "laundrybasket",
      "laundrysack", "pegs", "detergentpod", "stainremover", "wrinklereleaser", "lintroller", "sewingneedle", "safetybin", "trashliner", "bathroombin",
      "plungercaddy", "toiletcleantablet", "bleachtablet", "drainopener", "caulk", "sealant", "groutbrush", "squeegee", "showerwipe", "tilecleaner",
      "glasscleaner", "reeddiffuser", "essentialoildiffuser", "scentedcandle", "matches", "bathsaltsjar", "scoop", "footbath", "massager", "scalpbrush",
      "facialroller", "guasha", "drybrush", "bodyscrub", "shavingsoap", "stypticpencil", "talcumpowder", "babywash", "babyoil", "diapercream",
      "babywipes", "baththermometer", "bathduck", "bubbles", "faucetcover", "safetybar", "grabrail", "bathstep", "toiletstool", "mirrorcabinet",
      "magnifyingmirror", "ledmirror", "demister", "ventilationfan", "exhaustfan", "heaterlamp", "heatedtowelrail", "floorwaste", "grout", "tiles"
    ],

    living_room: [
      "sofa", "couch", "armchair", "recliner", "loveseat", "ottoman", "beanbag", "coffeetable", "endtable", "sideboard",
      "bookshelf", "cabinet", "tvstand", "television", "remote", "soundbar", "speaker", "subwoofer", "projector", "screen",
      "fireplace", "mantel", "hearth", "rug", "carpet", "curtain", "drapes", "blinds", "window", "door",
      "lamp", "floorlamp", "chandelier", "ceilingfan", "thermostat", "radiator", "airconditioner", "painting", "poster", "photograph",
      "clock", "vase", "flower", "houseplant", "planter", "cushion", "pillow", "throwblanket", "coaster", "ashtray",
      "magazine", "newspaper", "book", "boardgame", "puzzle", "cards", "toy", "petbed", "dogtoy", "catscratcher",
      "diffuser", "candle", "candlestick", "matches", "lighter", "bin", "basket", "tray", "figurine", "sculpture",
      "bowl", "potpourri", "telephone", "intercom", "router", "modem", "cable", "outlet", "extensioncord", "keyholder",
      "coatrack", "umbrellastand", "mirror", "wallclock", "displaycase", "barcart", "decanter", "wineglass", "aquarium", "terrarium",
      "birdcage", "easel", "piano", "guitar", "recordplayer", "vinyl", "album", "gong", "credenza", "bookcase",
      "nestingtables", "pouf", "daybed", "chaise", "rocker", "stool", "footrest", "pedestal", "shelf", "etagere",
      "secretarydesk", "bureau", "chest", "hutch", "valance", "shutters", "walltapestry", "sconce", "tracklight", "dimmer",
      "surroundsound", "amplifier", "turntable", "cassettedeck", "receiver", "mediaplayer", "dvdplayer", "consoletable", "gamingconsole", "gamepad",
      "vrheadset", "headphonehook", "sounddamping", "smartplug", "hometheater", "screenprojector", "screenshield", "coalbucket", "poker", "bellows",
      "lograck", "firewood", "grate", "ashbucket", "screensaver", "doorstop", "doormat", "keyrack", "mailtray", "catchall",
      "coatpegs", "shoebench", "slippersrack", "wallmirror", "driftwood", "artificialplant", "bonsai", "succulent", "fern", "orchid",
      "airplant", "terrariumbowl", "macrameranger", "plantstand", "spotlight", "uplight", "lava-lamp", "shadowbox", "picturecollage", "portrait",
      "sculpturestand", "globe", "hourglass", "musicbox", "metronome", "ukulele", "mandolin", "banjo", "synthesizer", "karaoke",
      "microphonestand", "headphones", "remoteholder", "coasterset", "winecooler", "icebucket", "whiskeystones", "decanterset", "cocktailshaker", "jigger",
      "bottleopener", "winerack", "glassholder", "barstool", "liqueurshelf", "cardshuffler", "dicecup", "pokerchips", "chessset", "checkers",
      "backgammon", "dominoes", "scrabbleboard", "jigsawmat", "dartboard", "darts", "foosballtable", "pinball", "beanbagchair", "gamingchair",
      "floorpillow", "throwpillow", "neckpillow", "heatingblanket", "weightedthrow", "footwarmer", "legrest", "backsupport", "traytable", "lapdesk",
      "booklight", "readingstand", "pennant", "banner", "trophycase", "diplomaframe", "souvenir", "trinketbox", "memorabilia", "statue",
      "bust", "carving", "woodcut", "weaving", "tapestry", "throwrug", "doorchime", "intercomsystem", "thermostatdial", "smokedetector",
      "fireextinguisher", "dustbuster", "vacuumcleaner", "sweeper", "lintroller", "featherduster", "polisher", "cleaningcloth", "airpurifierfilter", "fanswitch"
    ],

    office_study: [
      "desk", "chair", "computer", "laptop", "monitor", "keyboard", "mouse", "mousepad", "printer", "scanner",
      "shredder", "projector", "whiteboard", "marker", "eraser", "corkboard", "pushpin", "magnet", "bookshelf", "bookcase",
      "filingcabinet", "folder", "binder", "divider", "pocket", "notebook", "notepad", "journal", "planner", "calendar",
      "pen", "pencil", "highlighter", "ruler", "scissors", "stapler", "staples", "stapleremover", "paperclip", "binderclip",
      "rubberband", "tape", "tapedispenser", "glue", "gluestick", "sharpener", "calculator", "postit", "indexcard", "paper",
      "envelope", "stamp", "letteropener", "trashcan", "recyclingbin", "organizer", "tray", "holder", "cabinet", "safe",
      "key", "badge", "idcard", "lanyard", "briefcase", "backpack", "handbag", "wallet", "businesscard", "deskorganizer",
      "desklamp", "clock", "fan", "heater", "clipboard", "puncher", "seal", "inkpad", "compass", "protractor",
      "magnifyingglass", "microscope", "globe", "map", "bookend", "bookmark", "dictionary", "encyclopedia", "manual", "guidebook",
      "charcoal", "paintbrush", "canvas", "sketchbook", "palette", "easel", "filingdrawer", "hangingfolders", "tablabels", "portfolio",
      "documentholder", "lettertray", "penholder", "pencilcup", "stylus", "graphicstablet", "trackball", "headset", "webcam", "microphone",
      "shredderbag", "inkcartridge", "tonerbottle", "paperream", "cardstock", "tracingpaper", "graphpaper", "carbonpaper", "notecards", "envelopesealer",
      "postagescale", "packagingtape", "bubblewrap", "mailingtube", "utilityknife", "cuttingmat", "draftingtable", "draftingmachine", "t-square", "triangle",
      "stencil", "pantograph", "lighttable", "deskpad", "deskmat", "leatherblotter", "wristrest", "keyboardtray", "monitorstand", "laptopriser",
      "dockingstation", "harddrive", "flashdrive", "memorycard", "cardreader", "powerbank", "chargingstation", "cabletie", "cableclip", "cablemanagement",
      "surgeprotector", "smartplug", "router", "modem", "switch", "intercom", "whiteboardmarker", "dryeraser", "cleaningspray", "microfibercloth",
      "airduster", "dustblower", "shredderoil", "staplepuller", "holepunch", "threeholepunch", "singleholepunch", "eyelettool", "grommet", "rivet",
      "papercutter", "guillotine", "laminator", "laminatingpouches", "bindingmachine", "comb-binding", "spiralbinding", "presentationcover", "reportcover", "sheetprotector",
      "clipholder", "rubberstamp", "stampdampener", "waxseal", "sealingwax", "waxmeltingpot", "spoon", "calligraphyloader", "nib", "inkwell",
      "inkbottle", "blottingpaper", "fountainpen", "ballpointpen", "gelpen", "rollerballpen", "fineliner", "feltpen", "leadrefill", "mechanicalpencil",
      "eraserrefill", "kneadederaser", "artgum", "correctiontape", "correctionfluid", "whiteout", "rulersteel", "scalpel", "exactoknife", "replacementblades",
      "cuttingruler", "foldingruler", "caliper", "micrometer", "thermometer", "hygrometer", "barometer", "sandtimer", "desktoy", "newtonscradle",
      "fidgetspinner", "stressball", "rubikscube", "puzzle", "magnifyinglamp", "architectlamp", "goosenecklamp", "ledstrip", "smartbulb", "lightswitch",
      "extensioncord", "wirebasket", "wallgrid", "pegboard", "shelforganizer", "bookcart", "stepstool", "footrest", "backcushion", "seatcushion",
      "floorprotector", "chairmat", "casterwheels", "armrestcovers", "wastepaperbin", "recyclingbox", "compostbin", "shredderbox", "safecomb", "keybox"
    ],

    supermarket: [
      "cart", "basket", "aisle", "shelf", "checkout", "register", "scanner", "conveyor", "bag", "receipt",
      "coupon", "scale", "price", "barcode", "tag", "display", "freezer", "fridge", "bakery", "deli",
      "butcher", "produce", "grocery", "cannedfood", "cereal", "bread", "milk", "butter", "cheese", "yogurt",
      "egg", "meat", "beef", "pork", "chicken", "fish", "shrimp", "vegetable", "fruit", "apple",
      "banana", "orange", "grape", "tomato", "potato", "onion", "garlic", "lettuce", "carrot", "broccoli",
      "rice", "pasta", "flour", "sugar", "salt", "pepper", "oil", "vinegar", "sauce", "ketchup",
      "mustard", "mayonnaise", "spice", "herb", "coffee", "tea", "juice", "soda", "water", "beer",
      "wine", "snack", "chips", "cookie", "cracker", "chocolate", "candy", "nuts", "honey", "jam",
      "soap", "shampoo", "toothpaste", "detergent", "sponge", "paperplate", "napkin", "foil", "trashbag", "petfood",
      "diaper", "battery", "lightbulb", "magazine", "card", "flower", "icecream", "pizza", "frozenfood", "medicine",
      "divider", "scannergun", "receiptpaper", "creditcardreader", "registerdrawer", "scalesensor", "conveyorbelt", "shoppingbasket", "cartsilo", "pricetag",
      "clearancebin", "gondolashelf", "endcap", "refrigeratedcase", "freezerdoor", "delicounter", "meatcase", "seafoodcounter", "bakeryrack", "saladbar",
      "hotfoodbar", "rotisserieoven", "sushibar", "soupwell", "coffeegrinder", "bulkbin", "scoop", "funnel", "bagdispenser", "twisttie",
      "producebag", "paperbag", "plasticbag", "canvasbag", "insulatedbag", "boxcutter", "stockcart", "u-boat", "palletjack", "forklift",
      "shrinkwrap", "cardboardbaler", "handtruck", "dumpbin", "pegboard", "shelfdivider", "pushfeed", "labelholder", "signholder", "ceilingbanner",
      "aislesign", "floorsticker", "promotionalstand", "demonstrationtable", "samplecup", "toothpick", "sanitizerdispenser", "wipesdispenser", "trashbin", "bottlemachine",
      "canrecycler", "coinstar", "atm", "vendingmachine", "gumballmachine", "newspaperbox", "lotteryticket", "giftcardrack", "flowerbucket", "pottingsoil",
      "charcoal", "lighterfluid", "grillgrate", "cooler", "icebag", "dryice", "waterjug", "waterdispenser", "coffeefilter", "teabag",
      "sweetener", "creamer", "powderedmilk", "evaporatedmilk", "condensedmilk", "cocoapowder", "bakingpowder", "bakingsoda", "yeast", "cornstarch",
      "semolina", "oatmeal", "cornflakes", "muesli", "granola", "pancake-mix", "syrup", "honeyjar", "peanutbutter", "hazelnutspray",
      "marmalade", "fruitspread", "applesauce", "cannedpeaches", "cannedpineapple", "cannedtuna", "cannedsardines", "cannedsalmon", "cannedchicken", "cannedbeef",
      "cannedsoup", "cannedbeans", "cannedpeas", "cannedcorn", "cannedtomatoes", "tomatopaste", "spaghettisauce", "pesto", "alfredosauce", "gravymix",
      "bouilloncube", "beefbroth", "chickenbroth", "vegetablebroth", "ramen", "instantnoodles", "macaroni", "spaghetti", "lasagna", "penne",
      "quinoa", "barley", "couscous", "lentils", "chickpeas", "blackbeans", "kidneybeans", "pintobeans", "soybeans", "tofu",
      "seitan", "tempeh", "veggieburger", "frozenpeas", "frozencorn", "frozenberries", "frozenwaffles", "frozenfries", "frozenpizza", "frozenmeals",
      "icecreampint", "popsicles", "icecreamcone", "whippedcream", "sourcream", "creamcheese", "cottagecheese", "ricotta", "mascarpone", "mozzarella",
      "cheddar", "parmesan", "swisscheese", "provolone", "bluecheese", "goatcheese", "feta", "butterblock", "margarine", "lard",
      "oliveoil", "canolaoil", "vegetableoil", "coconutoil", "sesameoil", "balsamicvinegar", "applecidervinegar", "whitevinegar", "redwinevinegar", "soysauce",
      "teriyaki", "worcestershire", "hotsauce", "sriracha", "barbecuesauce", "saladdressing", "ranch", "italian-dressing", "thousandisland", "vinaigrette",
      "relish", "pickles", "olives", "capers", "jalapenos", "sauerkraut", "kimchi", "salsa", "guacamole", "tortillachips",
      "potatochips", "pretzel", "popcorn", "porkrinds", "cheese-puffs", "mixednuts", "peanuts", "almonds", "cashews", "pistachios",
      "walnuts", "sunflowerseeds", "pumpkinseeds", "raisins", "driedcranberries", "driedapricots", "driedfigs", "prunes", "beefjerky", "slimjim"
    ],

    restaurant_cafe: [
      "table", "chair", "booth", "bar", "stool", "menu", "bill", "receipt", "check", "tip",
      "waiter", "waitress", "server", "host", "hostess", "chef", "cook", "bartender", "dishwasher", "manager",
      "kitchen", "counter", "plate", "bowl", "cup", "saucer", "mug", "glass", "wineglass", "tumbler",
      "fork", "knife", "spoon", "napkin", "tablecloth", "placemat", "coaster", "straw", "toothpick", "tray",
      "teapot", "coffeepot", "pitcher", "carafe", "decanter", "cruet", "shaker", "grinder", "basket", "appetizer",
      "starter", "entree", "maincourse", "dessert", "side", "soup", "salad", "bread", "butter", "steak",
      "pasta", "pizza", "burger", "sandwich", "fries", "seafood", "sushi", "cake", "pie", "icecream",
      "coffee", "espresso", "latte", "cappuccino", "tea", "juice", "soda", "beer", "wine", "cocktail",
      "liquor", "water", "ice", "lemon", "sugar", "milk", "cream", "syrup", "honey", "apron",
      "uniform", "reservation", "chalkboard", "candle", "vase", "music", "lighting", "awning", "patio", "parasol",
      "boothdivider", "highchair", "boosterseat", "coatrack", "umbrellaholder", "menustand", "checkholder", "tipjar", "register", "pos-terminal",
      "receiptprinter", "cashdrawer", "buzzer", "pager", "orderticket", "ticketrail", "platingstation", "foodrunner", "busboy", "sommelier",
      "barista", "scullery", "greasetrap", "dumbwaiter", "servingtrolley", "traystand", "saladbowl", "soupbowl", "breadbasket", "butterdish",
      "saltshaker", "peppermill", "sugarbowl", "sweetenerpacket", "napkinholder", "tablecard", "reservationsign", "coffeefilter", "espresso-tamper", "knockbox",
      "frothingpitcher", "steamwand", "syruppump", "blender", "icemaker", "beertap", "keg", "co2tank", "sodagun", "icebucket",
      "winerack", "glasschiller", "shakertin", "strainer", "barspoon", "muddler", "jigger", "pourspout", "zester", "channelknife",
      "garnishtray", "lime", "olive", "maraschinocherry", "mint", "nutmeg", "cinnamon", "cocoashaker", "coffeegrinder", "tea-infuser",
      "teapotwarmers", "samovar", "waterboiler", "crepemaker", "waffleiron", "paninigrill", "toaster", "convectionoven", "fryer", "flat-top",
      "charbroiler", "salamander", "hoodrange", "firesuppression", "walk-in-freezer", "reach-in-fridge", "steamtable", "chafingdish", "fuelcanister", "sternowarmer",
      "servingfork", "servingspoon", "tongs", "cakecarver", "pizzacutter", "sushimat", "chopsticks", "chopstickrest", "sakebottle", "sakecup",
      "tea-cup", "matchawhisk", "matchabowl", "btea-shaker", "strawdispenser", "coffeestirrer", "cupholder", "carryoutbox", "doggybag", "takeoutcontainer",
      "deliverybag", "cloche", "platter", "saucedish", "gravyboat", "soupcup", "ramekin", "skewers", "fonduepot", "fonduefork",
      "table-runner", "placemat", "napkinring", "fingerbowl", "crumbscraper", "silentbutler", "servicebell", "orderpad", "dupepad", "pencil",
      "bussingtote", "dishrack", "washbasin", "sanitizerbucket", "dishsoap", "dryingrack", "apronstrings", "hairnet", "chefshat", "toque",
      "kitchenclog", "ovengloves", "towel", "polishingcloth", "floor-mat", "patioheater", "stringlights", "menuboard", "valetpodium", "intercom"
    ],

    hospital: [
      "bed", "wheelchair", "stretcher", "gurney", "crutches", "walker", "cane", "cast", "bandage", "gauze",
      "tape", "sling", "splint", "brace", "mask", "gloves", "gown", "scrubs", "coat", "stethoscope",
      "thermometer", "otoscope", "ophthalmoscope", "sphygmomanometer", "scale", "syringe", "needle", "vial", "ivpole", "ivbag",
      "catheter", "ventilator", "monitor", "defibrillator", "ultrasound", "xray", "mri", "ctscan", "microscope", "slide",
      "scalpel", "forceps", "tweezers", "scissors", "clamp", "tray", "basin", "sterilizer", "autoclave", "biohazardbin",
      "pill", "tablet", "capsule", "liquid", "ointment", "cream", "drops", "inhaler", "patch", "prescription",
      "chart", "folder", "record", "clipboards", "badge", "wristband", "pager", "phone", "ambulance", "siren",
      "emergencyroom", "operatingroom", "ward", "clinic", "pharmacy", "laboratory", "waitingroom", "reception", "desk", "chair",
      "sofa", "television", "magazine", "watercooler", "vendingmachine", "elevator", "stairs", "sign", "exit", "soap",
      "sanitizer", "disinfectant", "trashcan", "linens", "blanket", "pillow", "sheet", "towel", "tissue", "goggles",
      "faceshield", "respirator", "apron", "shoe-covers", "hairnet", "surgicalmask", "glovesbox", "scrubsbag", "labcoat", "lanyard",
      "idcard", "finger-splint", "neckcollar", "backboard", "headimmobilizer", "oxygenmask", "oxygentank", "flowmeter", "nasalcannula", "nebulizer",
      "suctionmachine", "aspirator", "ecg-machine", "leads", "electrodes", "pulseoximeter", "bloodpressurecuff", "glucometer", "lancet", "teststrip",
      "infusionpump", "syringe-driver", "dialysismachine", "hemostat", "retractor", "speculum", "tonguedepressor", "cottonswab", "alcoholprep", "iodineswab",
      "gauzepad", "tegaderm", "surgicaltape", "elasticbandage", "tourniquet", "bloodbag", "bloodtubing", "urinebag", "bedpan", "urinal", "washbasin",
      "emesisbasin", "specimencup", "hazardsbag", "sharpscontainer", "needlecutter", "pillcutter", "pillcrusher", "pilltray", "medicinecup", "dropper",
      "ointmenttube", "inhalerspacer", "crutchpads", "wheelchairramp", "patientlift", "trapezebar", "overbedtable", "callbutton", "ivhanger", "privacycurtain",
      "chartrack", "radiographviewbox", "lightbox", "anatomicalmodel", "skeleton", "eyewashstation", "safety-shower", "scrub-sink", "footpedal", "soapdispenser",
      "toweldispenser", "handdryer", "glovedispenser", "maskdispenser", "biohazardbag", "linencart", "utilitycart", "crashcart", "medicinecabinet", "safebox",
      "keybox", "pagercharger", "walkietalkie", "intercom", "telephonereceiver", "dictaphone", "clipboardpaper", "patientconsentform", "intakeform", "wristbandsprinter",
      "barcodescanner", "computeronwheels", "laptopcart", "tabletstand", "monitormount", "powerstrip", "ups-backup", "generator", "surgeprotector", "hospitalblanket",
      "drawsheet", "pillowcase", "washcloth", "patientgown", "paperroll", "examtable", "stirrups", "stepstool", "scalesensor", "heightrod",
      "snellenchart", "colorblindnessbook", "reflexhammer", "tuningfork", "penlight", "otoscopecone", "earspeculum", "nasalspeculum", "woodslamp", "dermatoscope",
      "scalepens", "stethoscopespare", "diaphragm", "eartips", "cuffbladder", "bulb", "valve", "manometer", "mercurytube", "ivconnector",
      "three-wayvalve", "extensiontubing", "butterflyneedle", "scalpveinset", "heparinlock", "salinelock", "catheterbag", "legstrap", "irrigationbottle", "sterilewater"
    ],

    airport: [
      "terminal", "gate", "concourse", "counter", "kiosk", "desk", "lounge", "runway", "tarmac", "hangar",
      "airplane", "jet", "helicopter", "cart", "bus", "train", "escalator", "elevator", "stairs", "walkway",
      "ticket", "boardingpass", "passport", "visa", "idcard", "wallet", "money", "card", "phone", "laptop",
      "baggage", "luggage", "suitcase", "backpack", "duffelbag", "briefcase", "handbag", "tag", "strap", "lock",
      "carousel", "conveyor", "trolley", "scale", "bin", "scanner", "metaldetector", "xray", "camera", "badge",
      "uniform", "pilot", "copilot", "steward", "stewardess", "crew", "agent", "officer", "guard", "janitor",
      "seat", "belt", "traytable", "pocket", "headset", "pillow", "blanket", "lifevest", "mask", "window",
      "aisle", "lavatory", "galley", "cockpit", "cabin", "cargo", "engine", "wing", "tail", "wheel",
      "sign", "screen", "monitor", "clock", "speaker", "announcement", "dutyfree", "shop", "restaurant", "cafe",
      "restroom", "bench", "trashcan", "chargingstation", "wifi", "map", "brochure", "newspaper", "magazine", "book",
      "checkincounter", "baggagecounter", "baggagedrop", "passportshelf", "kioskscreen", "kioskprinter", "boardingpassscanner", "gatesign", "gatelounge", "boardingbridge",
      "jetbridge", "airbridge", "gangway", "tarmacbus", "pushbacktug", "baggagetractor", "luggagecart", "luggageconveyor", "cargoloader", "cateringtruck",
      "fueltruck", "deicingtruck", "fireservicetruck", "followme-car", "runwaylights", "taxilights", "windsock", "radar", "controltower", "beacondome",
      "hangardoor", "helicopterpad", "runwaymarking", "taxiline", "barrier", "bollard", "stanchion", "beltbarrier", "signpost", "flightboard",
      "fids-screen", "digitalclock", "paspeaker", "microphone", "intercom", "securitydesk", "securitycamera", "bodycheckbooth", "metaldetectorgate", "xrayconveyor",
      "xraybin", "baggagescale", "luggagegauge", "passportsheet", "visasticker", "declarationform", "customsdesk", "quarantinebooth", "fingerprintscanner", "facialscanner",
      "idcardreader", "badgeholder", "lanyard", "radiotransceiver", "walkietalkie", "baton", "handcuffs", "flashlight", "megaphone", "whistle",
      "crewbag", "pilotcase", "garmentbag", "luggagezipper", "combinationlock", "keypad", "baggagetag", "barcodetag", "destinationtag", "prioritytag",
      "trolleybay", "trolleyreturn", "escalatorhandrail", "elevatorbutton", "elevatorcabin", "movingwalkway", "waitingbench", "armrest", "trashbin", "ashtray",
      "dutyfreeshelf", "perfumebottle", "alcoholbottle", "giftbox", "shoppingbag", "salescounter", "cashregister", "cardreader", "receiptprinter", "barstool",
      "diningtable", "menu", "napkindispenser", "straw", "coffeemug", "waterbottle", "chargingport", "usbcable", "poweroutlet", "wifirouter",
      "brochurerack", "mapdispenser", "newspaperstand", "magazinerack", "bookcase", "restroomsink", "faucet", "soapdispenser", "paperdispenser", "handdryer",
      "toiletpaper", "babyroomtable", "wheelchair", "stretcher", "emergencyphone", "fireextinguisher", "firehose", "alarmpull", "sprinklerhead", "smokedetector",
      "lifering", "evacuationsign", "exitdoor", "airlock", "curtain", "flightseat", "seatbelt", "buckle", "headrest", "armrestbutton",
      "reclinebutton", "safetycard", "airsicknessbag", "windowshade", "overheadbin", "readinglight", "airvent", "callbell", "flightphone", "galleycart",
      "coffeemaker", "warmingoven", "beveragedrawer", "galleyfaucet", "galleysink", "galleylatch", "lavatorysink", "lavatorytoilet", "toiletlever", "mirror"
    ],

    school: [
      "classroom", "desk", "chair", "table", "blackboard", "whiteboard", "chalk", "marker", "eraser", "pointer",
      "projector", "screen", "computer", "laptop", "tablet", "speaker", "microphone", "podium", "lectern", "bookshelf",
      "cabinet", "closet", "drawer", "bin", "trashcan", "recyclingbin", "clock", "calendar", "map", "globe",
      "poster", "chart", "bulletinboard", "pushpin", "magnet", "notebook", "notepad", "binder", "folder", "paper",
      "textbook", "workbook", "novel", "dictionary", "atlas", "encyclopedia", "pencil", "pen", "eraserrefill", "sharpener",
      "ruler", "compass", "protractor", "scissors", "glue", "tape", "stapler", "paperclip", "highlighter", "crayon",
      "paint", "brush", "canvas", "clay", "instrument", "piano", "guitar", "microscope", "slide", "beaker",
      "flask", "testtube", "rack", "scale", "thermometer", "magnifyingglass", "calculator", "backpack", "lunchbox", "thermos",
      "locker", "padlock", "key", "idcard", "lanyard", "uniform", "gymsuit", "sneakers", "whistle", "stopwatch",
      "trophy", "medal", "ribbon", "certificate", "diploma", "reportcard", "schedule", "syllabus", "homework", "exam",
      "auditorium", "gymnasium", "laboratory", "library", "cafeteria", "playground", "hallway", "corridor", "stairwell", "office",
      "infirmary", "restroom", "courtyard", "quadrangle", "bleachers", "stage", "curtain", "spotlight", "soundboard", "podiummic",
      "easel", "musicstand", "metronome", "tuningfork", "violin", "cello", "flute", "clarinet", "trumpet", "drum",
      "tambourine", "xylophone", "sheetmusic", "artdesk", "draftingtable", "cuttingmat", "palette", "sketchbook", "charcoal", "oilpastel",
      "watercolor", "acrylicpaint", "claywheel", "kiln", "sculptingtool", "smock", "sciencebench", "gasburner", "bunsenburner", "ringstand",
      "graduatedcylinder", "pipette", "dropper", "petridish", "forceps", "scalpel", "safetygoggles", "labapron", "eyewash", "fumehood",
      "periodic-table", "anatomicalskeleton", "torso-model", "prism", "tuning-fork", "batterypack", "alligatorclip", "wire", "switch", "ammeter",
      "voltmeter", "magnetbar", "ironfilings", "compass", "solenoid", "laserpointer", "microscopemount", "slideslip", "coverglass", "stainbottle",
      "lenspaper", "cleaningspray", "dustcover", "microscopecase", "calculatorcase", "abacus", "slide-rule", "mathset", "drawingcompass", "dividers",
      "chalkholder", "magneticboard", "smartboard", "dryeraser", "cleanerfluid", "corkstrip", "pushpinbox", "thumbtacks", "paperpunch", "holepunch",
      "stapleremover", "tapedispenser", "gluestick", "liquidglue", "rubbercement", "scissorsholder", "craftknife", "utilityblade", "pencilcup", "deskorganizer",
      "lettertray", "filingcabinet", "hangingfolder", "indexcard", "cardbox", "expandablefile", "binderclip", "paperclamp", "rubberband", "notebookcover",
      "looseleafpaper", "graphpaper", "tracingpaper", "constructionpaper", "coloredpencils", "markersset", "oilpastels", "watercolorpan", "paintbrushholder", "watercup",
      "clayknife", "apronstrings", "gymbag", "duffelbag", "athletictape", "conebox", "jumprope", "dodgeball", "basketball", "soccerball",
      "volleyball", "tennisracket", "tennisball", "badmintonracket", "shuttlecock", "pingpongpaddle", "pingpongball", "fitnessmat", "climbingrope", "pullupbar",
      "startingblock", "relaybaton", "shotput", "discus", "javelin", "highjumpmat", "measuringtape", "whistlelanyard", "stopwatchlanyard", "clipboard",
      "scorecard", "teamjersey", "pinnie", "shin-guards", "mouthguard", "helmet", "athleticcup", "lockercard", "idbadge", "badgeholder",
      "lanyardsnap", "registrationform", "reportcardenvelope", "diplomacase", "gradcap", "gradgown", "tassel", "yearbook", "classring", "alumnipin"
    ],

    park: [
      "bench", "table", "pavilion", "gazebo", "path", "trail", "bridge", "pond", "lake", "fountain",
      "stream", "river", "waterfall", "lawn", "grass", "flowerbed", "flower", "rose", "tulip", "daisy",
      "shrub", "bush", "tree", "oak", "pine", "maple", "willow", "palm", "leaf", "branch",
      "trunk", "root", "seed", "cone", "acorn", "berry", "mushroom", "fern", "moss", "ivy",
      "playground", "swing", "slide", "sandbox", "seesaw", "junglegym", "monkeybars", "merrygoround", "springrider", "climbingwall",
      "bucket", "shovel", "toy", "ball", "frisbee", "kite", "bicycle", "tricycle", "scooter", "skateboard",
      "rollerblades", "helmet", "pads", "leash", "collar", "harness", "treat", "bin", "trashcan", "recyclingbin",
      "dogwastebin", "bagdispenser", "sign", "map", "board", "post", "fence", "gate", "lamp", "lantern",
      "spotlight", "statue", "monument", "plaque", "restroom", "shelter", "picnicbasket", "blanket", "cooler", "grill",
      "charcoal", "lighter", "tongs", "plate", "cup", "napkin", "arbor", "pergola", "trellis", "planter",
      "flowerpot", "urn", "birdbath", "birdfeeder", "birdhouse", "squirrelfeeder", "beehive", "compostbin", "rainbarrel", "gardenhose",
      "sprinkler", "wateringcan", "spigot", "faucet", "bridgepost", "bridgerailing", "steppingstones", "gravelpath", "pavedwalkway", "dirtroad",
      "trailmarker", "hikingpole", "backpack", "canteen", "binoculars", "camera", "tripod", "sunhat", "sunglasses", "sunscreen",
      "insectspray", "picnicbench", "grillgrate", "charcoalbag", "lighterfluid", "matches", "barbecuespatula", "bastingbrush", "foodcontainer", "thermos",
      "waterbottle", "juicebox", "sandwichbag", "chipsbag", "paperplate", "plasticfork", "plasticspoon", "plasticcup", "napkinholder", "trashbag",
      "recyclingbag", "playgroundchains", "swingseat", "slideschute", "sandcastle-mold", "sieve", "sandrake", "toycar", "bubblesbottle", "bubblewand",
      "kitebox", "kitestring", "frisbeedisk", "soccershin-guards", "basketballhoop", "net", "tennisracket", "tennisball", "baseballglove", "baseballbat",
      "baseball", "soccerball", "football", "rugbyball", "volleyball", "bicyclerack", "bicyclelock", "bicyclesaddle", "bicyclebell", "bicyclebasket",
      "scooterdeck", "scooterhandlebars", "skateboarddeck", "skateboardwheels", "skateboardskating", "helmetstrap", "kneepads", "elbowpads", "wristguards", "dogcollar",
      "dogleash", "dogharness", "dogtag", "dogwhistle", "dogball", "dogfrisbee", "dogchew", "dogbowl", "waterdish", "poopbag",
      "poopscoop", "parkmap", "parkrules", "trailguide", "directionalsign", "historyplaque", "infoboard", "noticeboard", "flyer", "leaflet",
      "fencepost", "fencerail", "gatepost", "gatelatch", "gatekey", "lamp-post", "lanternhook", "ledbulb", "solarpanel", "batterypack",
      "fountaingrate", "fountainpump", "fountainnozzle", "pondliner", "pondfilter", "pondskimmer", "waterlily", "cattails", "duckdecoys", "duckfood",
      "fishfood", "statuebase", "plaquemount", "monumentarch", "sculpturespotlight", "restroomsink", "faucethead", "soapholder", "papertoweldispenser", "handdryer",
      "toiletpaperholder", "babychangingtable", "trashcanliner", "wastebasket", "shelterpost", "shelterroof", "pavilionbench", "paviliontable", "picnictablecover", "benchslat",
      "bencharmrest", "benchleg", "fencedoor", "boulder", "rockwall", "steppinglog", "balancebeam", "climbingrope", "cargo-net", "zip-line"
    ],

    gym: [
      "treadmill", "elliptical", "stationerybike", "rower", "stairclimber", "barbell", "dumbbell", "kettlebell", "weightplate", "collar",
      "rack", "bench", "press", "squatrack", "cablemachine", "pulley", "attachment", "handle", "rope", "bar",
      "mat", "yogamat", "block", "strap", "foamroller", "exerciseball", "medicineball", "bosuball", "slamball", "resistanceband",
      "jumprope", "stepdeck", "box", "ladder", "cones", "hurdles", "ring", "suspensiontrainer", "pullupbar", "dipstation",
      "locker", "shower", "sauna", "steambath", "pool", "towel", "scale", "mirror", "hairdryer", "watercooler",
      "bottle", "shaker", "supplement", "proteinpowder", "snack", "spraybottle", "disinfectant", "wipe", "trashcan", "clock",
      "timer", "stopwatch", "heartratemonitor", "smartwatch", "headphones", "earbuds", "phone", "armband", "holder", "bag",
      "duffelbag", "backpack", "sneakers", "shoes", "socks", "shorts", "pants", "leggings", "tshirt", "tanktop",
      "sportsbra", "jacket", "hoodie", "gloves", "belt", "straps", "wraps", "chalk", "membershipcard", "scanner",
      "turnstile", "desk", "register", "poster", "banner", "screen", "smithmachine", "legpress", "legextension", "legcurl",
      "hacksquat", "calfraise", "latpulldown", "rowmachine", "chestpress", "shoulderpress", "pecfly", "reardelt", "cablecrossover", "backextension",
      "abcoaster", "abbench", "romanbench", "preachercurlbay", "hyperextension", "dipbelt", "weighttree", "dumbbellshelf", "kettlebellrack", "bumperplates",
      "fractionalplates", "collarsnap", "springcollar", "spinlock", "ez-bar", "trapbar", "swissbar", "tricepsrope", "d-handle", "latbar",
      "straightbar", "v-bar", "stirruphandle", "ankle-strap", "neckharness", "wristroller", "handgripper", "gripboard", "chalkbowl", "weightliftingchalk",
      "stretchingmat", "yogabolster", "yogawheel", "massageball", "triggerpointball", "lacrosseball", "physioball", "stabilitydisc", "balanceboard", "wobbleboard",
      "agilityladder", "agilityhurdles", "agilitycones", "markerdiscs", "weightedvest", "paralllettes", "parachutes", "battleropes", "sled", "prowlersled",
      "sledharness", "parchmentpaper", "pegboard", "climbingpeg", "gymnasticsrings", "ringstraps", "abstraps", "hangingstraps", "bandsloop", "tubingband",
      "bandhandles", "dooranchor", "foamrollergrid", "vibratingroller", "massagegun", "nordicbench", "glute-ham-developer", "saunabench", "saunaheater", "saunabucket",
      "saunaladle", "saunathermometer", "steambathnozzle", "poolladder", "poollane-line", "poolbuoy", "poolkickboard", "poolnoodle", "poolgoggles", "swimcap",
      "toweldispenser", "towelsbin", "shampoodispenser", "bodywashdispenser", "scalepens", "mirrorswall", "hairdryerholder", "waterfountain", "bottlefiller", "shakerball",
      "supplementshaker", "proteinbar", "energydrink", "preworkoutpot", "creatinetub", "vitaminsbox", "spraybottleholder", "sanitizingwipes", "paperdispenser", "recyclingbin",
      "digitaltimer", "stopwatchlanyard", "wallclock", "heartratestrap", "phonemount", "cardreader", "desklamp", "membershipcardholder", "scannersensor", "turnstilever",
      "gymbag", "duffelstrap", "shoesbag", "sneakerlaces", "socksset", "shortsdrawstring", "sweatpants", "leggingspockets", "tshirtlogo", "tanktopstraps",
      "hoodiedrawstring", "gymgloves", "weightliftingbelt", "leverbelt", "prongbelt", "wristwraps", "elbowsleeves", "kneesleeves", "kneewraps", "liftingstraps",
      "hookgrips", "liquidchalk", "chalkbag", "gymbanner", "gymrulesboard", "lockershelf", "lockerkey", "lockertag", "padlock", "lockerbench"
    ],

    clothing: [
      "hanger", "rack", "wardrobe", "closet", "drawer", "shelf", "mirror", "mannequin", "shoehorn", "lintroller",
      "shirt", "tshirt", "polo", "blouse", "sweater", "cardigan", "hoodie", "sweatshirt", "vest", "jacket",
      "coat", "overcoat", "raincoat", "trenchcoat", "suit", "blazer", "tuxedo", "dress", "gown", "skirt",
      "pants", "trousers", "jeans", "shorts", "sweatpants", "leggings", "overalls", "jumpsuit", "pajamas", "nightgown",
      "underwear", "briefs", "boxers", "panties", "bra", "sportsbra", "socks", "stockings", "tights", "bathrobe",
      "shoes", "sneakers", "boots", "sandals", "slippers", "loafers", "heels", "flats", "oxfords", "wedges",
      "hat", "cap", "beanie", "beret", "fedora", "sunhat", "scarf", "gloves", "mittens", "earmuffs",
      "belt", "suspenders", "tie", "bowtie", "pocketsquare", "handkerchief", "umbrella", "handbag", "purse", "wallet",
      "backpack", "briefcase", "suitcases", "jewelry", "necklace", "bracelet", "ring", "earrings", "brooch", "watch",
      "glasses", "sunglasses", "hairpin", "hairtie", "headband", "apron", "uniform", "costume", "mask", "badge",
      "coathanger", "clothespin", "garmentrack", "wardrobedoor", "shoebox", "drawerdivider", "jewelrytray", "valetstand", "lintshaver", "shoetree",
      "dressshirt", "henleyshirt", "flannelshirt", "denimshirt", "camisole", "tanktop", "croptop", "turtleneck", "pullover", "poncho",
      "windbreaker", "leatherjacket", "denimjacket", "bomberjacket", "parka", "anorak", "downjacket", "peacoat", "dufflecoat", "blazerjacket",
      "eveninggown", "cocktaildress", "sundress", "maxidress", "wrapdress", "pleatedskirt", "pencilskirt", "maxiskirt", "miniskirt", "kilts",
      "chinos", "cargo-pants", "corduroypants", "slacks", "jeggings", "capripants", "boxershorts", "swimtrunks", "bikini", "onepiece",
      "camisoleset", "thermalunderwear", "longjohns", "undershirt", "corset", "garterbelt", "thong", "bralette", "anklesocks", "crewsocks",
      "kneehighs", "thighhighs", "fishnets", "leggingspant", "pajama-pants", "sleepshirt", "kimonorobe", "slippersocks", "running-shoes", "bootsankle",
      "combatboots", "chelseaboots", "cowboyboots", "rainboots", "snowboots", "clogs", "mules", "espadrilles", "flipflops", "slides",
      "brogues", "derbyshoes", "monkstraps", "boatshoes", "moccasins", "ballerinaflats", "stilettos", "platformshoes", "wedgesandals", "gladiatorsandals",
      "tophat", "panamahand", "strawhat", "buckethat", "visor", "baseballcap", "flatcap", "newsboycap", "turbans", "hijab",
      "ascot", "cravat", "cummerbund", "tieclip", "cufflinks", "collarstays", "suspendersclips", "beltbuckle", "keychain", "walletsafebox",
      "clutch", "tote", "messengerbag", "satchel", "duffelbag", "weekenderbag", "fannypack", "coinpurse", "cardholder", "passportcover",
      "jewelrybox", "necklacechain", "pendant", "charmbracelet", "bangle", "stackingrings", "studearrings", "hoopearrings", "cuffearrings", "nose-ring",
      "tiepin", "lapelpin", "boutonniere", "hairclaw", "barrette", "haircomb", "scrunchie", "tiara", "hairband", "fascinator",
      "readingglasses", "eyeglasscase", "lenscloth", "sunvisors", "parasol", "rainponcho", "trenchcoatbelt", "shoelaces", "bootlaces", "zipperpull",
      "cuffbutton", "snaps", "velcrostrap", "patches", "elbowpatches", "shoulderpads", "collarpin", "watchstrap", "watchbuckle", "pocketwatch",
      "lorgnette", "monocle", "handfan", "glovesbox", "mittenclip", "earmuffband", "scarfpin", "shawl", "pashmina", "stole",
      "bolero", "shrug", "sarong", "kaftan", "overallsstraps", "apronstrings", "maskstrap", "badgeclip", "lanyardsnap", "costumehat"
    ],

    street: [
      "sidewalk", "pavement", "curb", "gutter", "crosswalk", "intersection", "corner", "alley", "lane", "highway",
      "road", "street", "avenue", "boulevard", "driveway", "parkinglot", "parkingspace", "parkingmeter", "stoplight", "trafficsignal",
      "sign", "stopsign", "yieldsign", "speedlimitsign", "onewaysign", "streetlights", "lamppost", "utilitypole", "wire", "cable",
      "manhole", "cover", "drain", "grate", "hydrant", "firehydrant", "mailbox", "trashcan", "recyclingbin", "bench",
      "busstop", "shelter", "subwaystation", "entrance", "exit", "stairs", "escalator", "elevator", "turnstile", "ticketmachine",
      "booth", "newsstand", "kiosk", "billboard", "poster", "banner", "flag", "flagpole", "tree", "shrub",
      "flowerbed", "planter", "fence", "gate", "wall", "building", "skyscraper", "storefront", "awning", "window",
      "door", "steps", "ramp", "railing", "balcony", "roof", "chimney", "antenna", "satellite", "securitycamera",
      "car", "truck", "bus", "taxi", "motorcycle", "scooter", "bicycle", "pedestrian", "cyclist", "runner",
      "officer", "guard", "sweeper", "siren", "alarm", "puddle", "pothole", "debris", "litter", "pavementmarking",
      "crosswalkstrip", "bike-lane", "bus-lane", "median", "trafficcircle", "roundabout", "overpass", "underpass", "tunnel", "tollbooth",
      "tollgate", "speedbump", "rumblestrip", "guardrail", "jerseybarrier", "bollard", "stanchion", "chainlink", "barricade", "trafficcone",
      "warningtape", "streetname-sign", "streetnumber-sign", "stopsignpost", "signalbox", "controllerbox", "powerbox", "transformer", "telephonepole", "wires",
      "manholehook", "stormdrain", "sewerpipe", "watermain", "gasvalve", "hydrantwrench", "mailslop", "mailboxtag", "trashbinliner", "wastebasket",
      "busstopsign", "busshelterbench", "subwaystairs", "subwayplatform", "subwaytrack", "thirdrail", "ticketgate", "cardreader", "subwaymap", "subwayclock",
      "tokenbooth", "newsstandrack", "kioskscreen", "kioskprinter", "billboardframe", "posterframe", "bannermount", "flagpolepulley", "flagclip", "treewrap",
      "treegrate", "treeguard", "shrubshears", "planterbox", "planterpot", "fencepost", "fencerail", "gatepost", "gatelatch", "gatekey",
      "wallbricks", "wallstone", "buildingfacade", "buildinglobby", "buildingelevator", "revolvingdoor", "storefrontwindow", "awningframe", "windowframe", "windowsill",
      "doorhandle", "doorbell", "intercom", "stepsrail", "ramprail", "balconyrail", "roofshingle", "roofgutter", "drainspout", "chimneycap",
      "antennamount", "satellitedish", "cameramount", "cameralens", "carwheels", "carbumper", "carheadlight", "carwindshield", "licenceplate", "truckbed",
      "truckcab", "buswheels", "busdoor", "buswindow", "taximeter", "taxisign", "motorcycleengine", "motorcyclewheels", "scooterdeck", "scooterhandlebars",
      "bicyclewheel", "bicyclepedal", "bicyclechain", "bicyclesaddle", "bicyclehandlebars", "bicyclebell", "bicyclelock", "pedestrianbutton", "crosswalksignal", "runningpath",
      "officerbadge", "officeruniform", "officerbaton", "officerwhistle", "guardshed", "guarddesk", "streetcleanertruck", "streetcleanerbrush", "streetcleanerhose", "firedepartment",
      "firesiren", "policecar", "policesiren", "ambulancesiren", "waterpuddle", "asphaltpuddle", "gravelpuddle", "potholerid", "debrisbox", "litterbin",
      "flyer", "leaflet", "brochure", "coupon", "ticket", "coins", "bills", "wallet", "bag", "backpack"
    ],

    garden: [
      "soil", "dirt", "fertilizer", "compost", "mulch", "seed", "seedling", "sprout", "plant", "flower",
      "shrub", "bush", "tree", "vine", "weed", "grass", "lawn", "sod", "flowerbed", "border",
      "pot", "planter", "saucer", "urn", "windowbox", "trellis", "arbor", "pergola", "gazebo", "greenhouse",
      "shed", "workshop", "bench", "table", "chair", "hammock", "swing", "parasol", "umbrella", "fountain",
      "pond", "lake", "waterfall", "stream", "birdbath", "birdfeeder", "birdhouse", "beehive", "compostbin", "rainbarrel",
      "hose", "nozzle", "reel", "sprinkler", "wateringcan", "spigot", "faucet", "shovel", "spade", "trowel",
      "fork", "rake", "hoe", "cultivator", "weeder", "shears", "pruners", "loppers", "saw", "clippers",
      "mower", "lawnmower", "trimmer", "edger", "blower", "leafblower", "wheelbarrow", "cart", "bucket", "tub",
      "gloves", "boots", "apron", "kneelingpad", "hat", "sunglasses", "sunscreen", "insectrepellent", "pesticide", "herbicide",
      "path", "steppingstone", "gravel", "paver", "deck", "patio", "fence", "gate", "latch", "lock",
      "pottingsoil", "peatmoss", "perlite", "vermiculite", "bonemeal", "bloodmeal", "lime", "manure", "seedpacket", "seediit",
      "sapling", "graft", "cutting", "rootball", "rhizome", "bulb", "corm", "tuber", "runner", "stolons",
      "succulent", "cactus", "fern", "moss", "ivy", "climber", "groundcover", "ornamentalgrass", "wildflowers", "herbs",
      "annuals", "perennials", "evergreen", "deciduous", "conifer", "topiary", "bonsai", "hedge", "windbreak", "espalier",
      "terracottapot", "ceramicplanter", "plasticpot", "peatpot", "hangingbasket", "wallplanter", "plantstand", "saucerliner", "drainagegrate", "trellissupport",
      "arborarch", "pergolaroof", "gazebobench", "greenhouseshelf", "greenhousevent", "greenhouseheater", "sheddoor", "shedwindow", "workbench", "pegboard",
      "toolrack", "gardenbench", "patiotable", "patiochair", "deckchair", "lounger", "sunbed", "hammockstand", "swingset", "parasolbase",
      "umbrellastand", "fountainpump", "fountainnozzle", "fountaingrate", "pondliner", "pondfilter", "pondskimmer", "waterpump", "waterfallrocks", "streambed",
      "birdbathpedestal", "seedfeeder", "suetfeeder", "nectarfeeder", "squirrelbaffle", "birdhousepole", "beehivebox", "beeframe", "queenexcluder", "compostaerator",
      "compostthermometer", "rainbarrelspigot", "rainbarrelscreen", "diverter", "hosepipe", "hosereel", "hosecart", "hosesplitter", "hosemender", "spraygun",
      "wandnozzle", "oscillatingsprinkler", "rotarysprinkler", "dripsystem", "dripline", "emitter", "soakerhose", "timersprinkler", "spigothandle", "faucetadapter",
      "shovellever", "spadehandle", "trowelblade", "handfork", "cultivatortines", "bowrake", "leafrake", "thatchrake", "drawhoe", "scufflehoe",
      "weedingtool", "dandeliondigger", "pruningshears", "bypasspruners", "anvilpruners", "hedgeshears", "loppershandles", "pruningsaw", "bowsaw", "foldingsaw",
      "polepruner", "grasstrimmer", "stringtrimmer", "trimmerline", "lawnedger", "edgerblade", "leafblowerbag", "wheelbarrowwheel", "wheelbarrowtray", "wheelbarrowhandles",
      "dumpcart", "utilitycart", "bucketliner", "plasticpail", "gardentub", "trug", "glovesleather", "bootsrubber", "bootscraper", "bootjack",
      "kneeler", "sunhatstraw", "insectmesh", "sprayer", "pressuresprayer", "pesticidebottle", "herbicidesprayer", "slugpellets", "weedbarrier", "landscapingfabric",
      "fabricstaples", "gravelgrid", "paverbase", "paversand", "deckingplanks", "deckingclips", "patiobricks", "fencerail", "fencepanel", "fencepostcap"
    ],

    garage: [
      "car", "motorcycle", "bicycle", "scooter", "truck", "suv", "trailer", "tire", "wheel", "jack",
      "jackstand", "ramp", "creeper", "oil", "funnel", "filter", "wrench", "socket", "ratchet", "screwdriver",
      "pliers", "wirestripper", "crimper", "cutter", "hammer", "mallet", "sledgehammer", "saw", "hacksaw", "handsaw",
      "drill", "drillpress", "drillbit", "driver", "impactwrench", "grinder", "sander", "circularsaw", "jigsaw", "mitersaw",
      "tablesaw", "compressor", "airhose", "nailgun", "stapler", "generator", "battery", "charger", "jumpercables", "workbench",
      "vise", "clamp", "anvil", "toolbox", "chest", "cabinet", "shelf", "rack", "pegboard", "hook",
      "bin", "container", "organizer", "drawer", "tote", "bucket", "sponge", "rag", "towel", "degreaser",
      "cleaner", "polish", "wax", "soap", "hose", "nozzle", "broom", "dustpan", "trashcan", "recyclingbin",
      "ladder", "stepladder", "stool", "flashlight", "worklight", "headlamp", "extensioncord", "powerstrip", "heater", "fan",
      "fireextinguisher", "firstaidkit", "goggles", "gloves", "mask", "earmuffs", "apron", "carwheel", "tiretread", "tirevalve",
      "hubcap", "lugnut", "wheelrim", "motorcyclehelmet", "motorcyclechain", "motorcyclesaddle", "motorcycle handlebars", "bicyclewheel", "bicyclepedal", "bicyclechain",
      "bicyclesaddle", "bicyclehandlebars", "bicyclebell", "bicyclelock", "scooterdeck", "scooterhandlebars", "scooterwheels", "truckbed", "truckcab", "suvroofbox",
      "suvbike-rack", "trailerhitch", "trailercoupler", "trailerlights", "hydraulicjack", "scissoringjack", "bottlejack", "jackstandpin", "jackstandpad", "rampstop",
      "rampslope", "creeperwheels", "creeperpillow", "motor-oil", "transmissionfluid", "brakefluid", "steeringfluid", "coolant", "antifreeze", "windshieldwasher",
      "oilfilter", "airfilter", "cabinfilter", "fuelfilter", "oilfilterwrench", "funnelhose", "funnelspout", "oilpan", "oildrippan", "oilabsorbent",
      "combinationwrench", "adjustablewrench", "pipewrench", "torquewrench", "allenwrench", "hexkey", "socketsize", "socketadapter", "socketextension", "ratchethandle",
      "screwdriverslot", "screwdriverphillips", "screwdriverflathead", "screwdriverprecision", "pliersneedle-nose", "pliersslip-joint", "plierslocking", "pliersgroove-joint", "wirestrippertool", "crimpingtool",
      "cutterwire", "cutterbolt", "clawhammer", "ballpeenhammer", "rubbermallet", "woodenmallet", "sledgehammerhandle", "hacksawblade", "handsawteeth", "copingsaw",
      "powerdrill", "cordlessdrill", "drillchuck", "drillkey", "drillpressbench", "drillpresstable", "twistdrillbit", "spadebit", "hole-saw", "impactdriver",
      "impactsocket", "benchgrinder", "anglegrinder", "grindingwheel", "wirewheel", "beltsander", "orbitalsander", "sandpaper", "sandpaperblock", "circularsawblade",
      "jigsawblade", "mitersawblade", "tablesawblade", "tablesawfence", "tablesawmiter", "compressortank", "compressorgauge", "compressorregulator", "airhosereel", "airhosefitting",
      "pneumaticnailer", "pneumaticstapler", "gasgenerator", "invertergenerator", "carbattery", "motorcyclebattery", "battery charger", "batterytester", "jumpercableclamps", "workbenchdrawer",
      "workbenchedit", "benchvise", "barclamp", "c-clamp", "springclamp", "pipeclamp", "anvilhorn", "anvilface", "toolboxhandle", "toolboxlatch",
      "toolchestdrawer", "toolchestlock", "metalcabinet", "woodshelf", "wire-rack", "pegboardhook", "pegboardbasket", "binboxes", "storagecontainers", "drawerdivider",
      "totecontainer", "metalbucket", "carsponges", "microfiberrag", "shoptowel", "cleanerspray", "brakeclaner", "carburetorcleaner", "wd-40", "penetratingoil",
      "lubricant", "siliconespray", "greasegun", "greasetube", "carpolish", "carwax", "carsoap", "gardenhose", "spraynozzle", "pushbroom",
      "whiskbroom", "dustpanhandle", "trashcanliner", "recyclingbinbox", "extensionladder", "stepstoolbench", "shopstool", "worklightstand", "ledworklight", "magneticflashlight",
      "powerstripcable", "spaceheater", "boxfan", "firstaidbox", "safetygoggles", "nitrilegloves", "workgloves", "dustmask", "respiratormask", "apronpockets"
    ],

    library: [
      "book", "novel", "biography", "encyclopedia", "dictionary", "atlas", "almanac", "directory", "catalog", "index",
      "journal", "magazine", "newspaper", "periodical", "manuscript", "document", "file", "archive", "portfolio", "binder",
      "folder", "paper", "notebook", "notepad", "bookmark", "bookplate", "barcode", "tag", "spine", "cover",
      "jacket", "pages", "leaf", "illustration", "photograph", "map", "chart", "poster", "microfilm", "microfiche",
      "reader", "viewer", "scanner", "printer", "photocopier", "computer", "laptop", "tablet", "headphones", "audiobook",
      "cd", "dvd", "cassette", "record", "player", "monitor", "keyboard", "mouse", "desk", "chair",
      "table", "carrel", "booth", "sofa", "armchair", "bench", "stool", "beanbag", "bookshelf", "bookcase",
      "stack", "row", "aisle", "shelf", "divider", "bookend", "cart", "trolley", "bin", "box",
      "counter", "register", "computerbadge", "card", "form", "slip", "receipt", "fine", "fee", "stamp",
      "inkpad", "calendar", "clock", "sign", "posterdisplay", "bulletinboard", "thumbtack", "pushpin", "tape", "dispenser",
      "stapler", "staples", "paperclip", "rubberband", "pencil", "pen", "highlighter", "eraser", "sharpener", "ruler",
      "scissors", "glue", "envelope", "label", "sticker", "pouch", "sleeve", "bag", "backpack", "briefcase",
      "totebag", "wallet", "key", "safe", "locker", "padlock", "closet", "cabinet", "drawer", "wardrobe",
      "hanger", "rack", "binliner", "trashcan", "recyclingbin", "watercooler", "vendingmachine", "payphone", "elevator", "stairs",
      "steps", "handrail", "exit", "door", "window", "blinds", "curtain", "rug", "carpet", "lamp",
      "ceilingfan", "radiator", "airconditioner", "thermostat", "router", "modem", "wifi", "outlet", "switch", "extensioncord",
      "hardback", "paperback", "audiobookplayer", "cdplayer", "dvdplayer", "recordplayer", "vinyl", "cassettedeck", "cassetteplayer", "microfilmreader",
      "microfichereader", "microfilmroll", "microfichesheet", "opac-terminal", "catalogcard", "catalogdrawer", "catalogcabinet", "callnumber", "shelfmarker", "shelfguide",
      "shelfdivider", "bookendmetal", "bookendwood", "bookcartwheels", "bookcarttray", "bookcarthandle", "booktrolley", "drop-box", "bookreturnbox", "circulationdesk",
      "receptiondesk", "referencedesk", "studycarrel", "studytable", "loungechair", "beanbagchair", "pouf", "accentchair", "desklamp", "floorlamp",
      "chandelier", "pendantlight", "wallclock", "calendarholder", "notecard", "indexcardholder", "signholder", "displaystand", "brochurerack", "noticeboard",
      "suggestionbox", "donationbox", "librarycard", "barcodescanner", "receiptprinter", "cashdrawer", "stampdampener", "inkwell", "fountainpen", "magnifyingglass",
      "pageturner", "bookholder", "readingstand", "bookrest", "booklight", "readingglasses", "eyeglasscase", "lenscloth", "dustjacket", "bookspine",
      "bookpages", "bookbinding", "bookglue", "repairtape", "leathercover", "manuscriptroll", "scroll", "scrollcase", "parchment", "papyrus",
      "vellum", "documentbox", "archivalbox", "acidfreefolder", "acidfreepaper", "photographholder", "slidefolder", "negativeholder", "mapcabinet", "mapdrawer",
      "blueprintcabinet", "blueprintdrawer", "flatfile", "portfoliobinder", "presentationfolder", "clippaper", "paperpunch", "holepunch", "spiralbinder", "comb-binder",
      "laminator", "laminatingpouch", "trimmer", "papercutter", "guillotine", "utilityknife", "cuttingmat", "rulermetal", "rulerscale", "draftingtable"
    ],

    beach: [
      "sand", "dune", "beach", "shore", "coast", "ocean", "sea", "wave", "tide", "surf",
      "current", "foam", "spray", "water", "saltwater", "shells", "seashell", "clam", "oyster", "snail",
      "crab", "hermitcrab", "starfish", "jellyfish", "fish", "seagull", "pelican", "bird", "seaweed", "kelp",
      "driftwood", "pebble", "stone", "rock", "cliff", "cave", "pier", "dock", "jetty", "boardwalk",
      "towel", "blanket", "mat", "umbrella", "parasol", "tent", "cabana", "chair", "lounger", "hammock",
      "cooler", "ice", "bottle", "can", "cup", "straw", "napkin", "plate", "food", "snack",
      "swimsuit", "bikini", "trunks", "rashguard", "wetsuit", "hat", "sunglasses", "sunscreen", "lotion", "oil",
      "sandals", "flipflops", "slippers", "shoes", "bag", "totebag", "backpack", "pouch", "phone", "camera",
      "speaker", "frisbee", "ball", "volleyball", "net", "paddle", "racket", "kite", "bucket", "shovel",
      "mold", "rake", "castle", "float", "raft", "tube", "ring", "goggles", "snorkel", "fins",
      "sandbar", "sandgrain", "sandbucket", "sandshovel", "sandcastle", "sanddune", "sandtracks", "sandparticle", "sandpit", "shellsbeach",
      "seashells", "conch", "scallop", "mussel", "barnacle", "seasnail", "hermitcrabhaven", "fiddlercrab", "horseshoecrab", "jellyfishsting",
      "starfisharms", "seagullfeather", "seagullbeak", "pelicanpouch", "sandpiper", "seaweedtangle", "kelpbed", "kelpforest", "driftwoodlog", "driftwoodbranch",
      "beachpebble", "shingle", "beachstone", "coastalrock", "sea-cliff", "sea-cave", "tidepool", "rockpool", "dockpost", "dockplank",
      "jettyboulder", "boardwalkplank", "boardwalkrailing", "pierpost", "pierrailing", "beachbench", "beachtowel", "beachblanket", "beachmat", "beachumbrella",
      "parasolstand", "beachbooth", "beachcabana", "beachchair", "beachlounger", "beachhammock", "hammockstand", "icebucket", "icepack", "coolerbox",
      "waterbottle", "drinkcan", "plasticcup", "papercup", "bamboostraw", "papernapkin", "paperplate", "beachsnack", "sandwich", "fruitcup",
      "beachswimsuit", "bikinitop", "bikinibottom", "swimtrunks", "rashguardshirt", "neoprene-wetsuit", "beachhat", "strawhat", "sunvisor", "baseballcap",
      "polarised-sunglasses", "eyeglassstrap", "sunscreenbottle", "sunscreencream", "sunscreenspray", "aftersunlotion", "tanningoil", "beachsandals", "beachflipflops", "watershoes",
      "beachbag", "meshbag", "waterproofpouch", "waterproofcase", "underwatercamera", "actioncamera", "bluetoothspeaker", "waterproofspeaker", "frisbeedisk", "beachball",
      "beachvolleyball", "volleyballnet", "paddleboard", "paddleracket", "kitespooling", "kitestring", "beachbucket", "beachshovel", "sandmold", "sandrake",
      "sandcastle-tower", "swimfloat", "inflatableraft", "swimtube", "swimring", "lifevest", "swimmask", "snorkeltube", "swimfins", "divinggoggles",
      "surfboard", "surfboardleash", "surfboardfins", "surfboardwax", "bodyboard", "bodyboardleash", "skimboard", "paddleboardpaddle", "paddleboardleash", "kayak",
      "kayakpaddle", "kayakseat", "windsurfer", "windsurfboard", "windsurfsail", "windsurfmast", "kitesurfer", "kitesurfboard", "kitesurfkite", "kitesurfharness",
      "catamaran", "catamaransail", "catamaranhull", "lifeguardchair", "lifeguardsand", "lifeguardbuoy", "lifeguardboard", "lifeguardwhistle", "lifeguardmegaphone", "firstaidkit",
      "warningflag", "redflag", "yellowflag", "greenflag", "purpleflag", "beachsigns", "beachrules", "trashcan", "recyclingbin", "beachshower",
      "footwash", "restroom", "changingroom", "beachbar", "beachcafe", "icecreamcart", "snackshack", "rentalkiosk", "toursign", "beachparking"
    ],

    bank: [
      "vault", "safe", "safedepositbox", "drawer", "till", "register", "counter", "desk", "chair", "sofa",
      "atm", "machine", "screen", "keyboard", "keypad", "cardreader", "dispenser", "camera", "securitycamera", "alarm",
      "sensor", "detector", "gate", "barrier", "turnstile", "door", "window", "glass", "bulletproofglass", "sign",
      "slip", "form", "application", "contract", "agreement", "statement", "document", "record", "file", "folder",
      "binder", "paper", "pen", "pencil", "calculator", "computer", "monitor", "printer", "scanner", "shredder",
      "money", "cash", "currency", "bill", "note", "coin", "penny", "nickel", "dime", "quarter",
      "dollar", "gold", "silver", "bullion", "bar", "bag", "sack", "envelope", "pouch", "wallet",
      "card", "debitcard", "creditcard", "giftcard", "idcard", "license", "passport", "badge", "uniform", "vest",
      "guard", "officer", "manager", "teller", "clerk", "accountant", "advisor", "broker", "client", "customer",
      "line", "queue", "number", "ticket", "dispenser", "clock", "calendar", "rateboard", "poster", "brochure",
      "vaultdoor", "vaultwheel", "vaultlock", "vaultshelves", "safebox", "depositorybox", "cashdrawer", "tilltray", "cashregister", "countertop",
      "atmscreen", "atmkeypad", "atmcardreader", "atmdispenser", "atmreceipt", "atmcamerashield", "securityalarm", "alarmsensor", "alarmbutton", "motiondetector",
      "entrygate", "exitbarrier", "turnstilever", "glassbarrier", "bulletproofshield", "signpost", "intercom", "telephonereceiver", "depositform", "withdrawalform",
      "checkbook", "checkbookcover", "bankcheck", "personalcheck", "cashierscheck", "promissorynote", "receiptslip", "transactionrecord", "loanapplication", "mortgagecontract",
      "signaturepad", "idscanner", "flatbedscanner", "documentfeeder", "shredderbin", "moneycounter", "coincounter", "coinsonter", "coinsbag", "billcounter",
      "billstraps", "cashbox", "cashbag", "bankenvelope", "zipperpouch", "zippertote", "briefcase", "handbag", "walletleather", "cardholder",
      "debitcardchip", "creditcardstripe", "smartcard", "tokengkey", "idbadge", "badgeholder", "lanyard", "securityuniform", "bulletproofvest", "guardbadge",
      "manageroffice", "tellerwindow", "clerkdesk", "advisorchair", "clientsofa", "customerline", "queuebarrier", "queuenumber", "ticketdispenser", "rateboardled",
      "posterframe", "brochurerack", "penholder", "pencilcup", "paperweight", "deskorganizer", "lettertray", "filingcabinet", "hangingfolder", "folderlabels",
      "binderclip", "paperclip", "rubberband", "stapler", "staples", "stapleremover", "tapedispenser", "gluestick", "scissors", "ruler",
      "calculatorcase", "deskpad", "deskmat", "mousepad", "keyboardtray", "monitorstand", "laptopriser", "powerstrip", "surgeprotector", "ups-backup",
      "wallclock", "deskclock", "calendarholder", "notecard", "memopad", "trashcanliner", "wastebasket", "recyclingbinbox", "watercooler", "vendingmachine",
      "coinpenny", "coinnickel", "coindime", "coinquarter", "coindollar", "goldbullion", "goldbar", "silverbar", "silvercoins", "depositbag",
      "armoredtruck", "armoredcar", "duffelbag", "keychain", "safecombination", "safekey", "vaultkey", "depositboxkey", "signagesheet", "lobbybench"
    ],

    post_office: [
      "letter", "envelope", "postcard", "card", "package", "parcel", "box", "tube", "bag", "sack",
      "pouch", "wrapper", "paper", "cardboard", "bubblewrap", "tape", "tapedispenser", "glue", "gluestick", "string",
      "rope", "twine", "scissors", "cutter", "knife", "pen", "pencil", "marker", "highlighter", "ruler",
      "scale", "balance", "weights", "stamp", "postagestamp", "sticker", "label", "barcode", "trackingnumber", "receipt",
      "invoice", "form", "slip", "clipboard", "pad", "counter", "desk", "chair", "table", "bench",
      "bin", "basket", "tray", "cart", "trolley", "hamper", "sortingrack", "shelf", "cabinet", "safe",
      "key", "lock", "mailbox", "postbox", "dropbox", "slot", "chute", "door", "window", "glass",
      "screen", "monitor", "keyboard", "mouse", "printer", "scanner", "register", "cashdrawer", "money", "card",
      "terminal", "reader", "badge", "uniform", "satchel", "truck", "van", "car", "bicycle", "motorcycle",
      "carrier", "clerk", "manager", "customer", "queue", "prioritymail", "expressmail", "certifiedmail", "registeredmail", "insuranceslip",
      "returnreceipt", "customsdeclaration", "shippinglabel", "addresslabel", "fragilesticker", "thiswayup", "handleswithcare", "bubblemailer", "paddedenvelope", "manilaenvelope",
      "claspenvelope", "windowenvelope", "letteropener", "sealingwax", "waxseal", "waxmeltingpot", "waxmeltingpotspoon", "stringtwine", "ropetie", "papercutter",
      "guillotine", "utilityknife", "craftknife", "replacementblades", "cuttingmat", "rulermetal", "measuringtape", "postagescale", "digitalscale", "platformscale",
      "scalecalibration", "scalegauge", "stampbook", "stamproll", "stampdispenser", "stampdampener", "watercup", "spongecup", "stickerroll", "stickerdispenser",
      "barcodetag", "barcodescanner", "handheldscanner", "receiptprinter", "receiptpaper", "invoicefolder", "shippinginvoice", "claimslip", "noticetag", "postalslip",
      "clipboardpaper", "memopad", "notebook", "notepad", "countertop", "counterbarrier", "receptiondesk", "clerkchair", "lobbybench", "waitingchair",
      "sortingbin", "sortingbasket", "sortingtray", "mailcart", "mailtrolley", "mailhamper", "mailbag", "mailsack", "courierbag", "couriersatchel",
      "sortingracklabels", "mailcase", "pigeonhole", "shelfdivider", "filingcabinet", "hangingfolder", "folderslips", "safebox", "keybox", "padlock",
      "combinationlock", "keyring", "keychain", "mailboxslot", "mailboxdoor", "mailboxflag", "postboxslot", "postboxdoor", "dropboxslot", "dropboxdoor",
      "mailchute", "lobbypost", "entrydoor", "exitdoor", "counterwindow", "glassbarrier", "bulletproofshield", "lobbycounter", "checkoutregister", "cashregisterdrawer",
      "cashbox", "creditcardreader", "signaturepad", "cardreader", "barcodereader", "scannersensor", "badgeholder", "lanyard", "lanyardsnap", "postaluniform",
      "postalcap", "postalbag", "postalsatchel", "courieruniform", "courierjacket", "courierbackpack", "deliverytruck", "deliveryvan", "deliverycar", "deliverybicycle",
      "deliverymotorcycle", "mailcarrier", "postalclerk", "postmaster", "branchmanager", "customerservices", "customsagent", "customsofficer", "quarantineinspector", "linesign",
      "queuebarrier", "queuenumber", "ticketdispenser", "ratetable", "ratecalculator", "wallclock", "deskclock", "calendarholder", "noticeboard", "posterdisplay",
      "brochurerack", "leafletdispenser", "suggestionbox", "donationbox", "wastebasket", "trashbin", "recyclingbinbox", "compostbin", "watercooler", "vendingmachine"
    ]
  }
};